services:
  - type: web
    name: saleor-storefront
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URI
        value: https://saleor-backend.onrender.com/graphql/
      - key: NEXT_PUBLIC_API_URL
        value: https://saleor-backend.onrender.com/graphql/
      - key: NODE_ENV
        value: production
