# Generated by Django for QabiFly User Extensions

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('BUYER', 'BUYER'),
                    ('SHOPKEEPER', 'SHOPKEEPER'),
                    ('DELIVERY_BOY', 'DELIVERY_BOY'),
                    ('ADMIN', 'ADMIN'),
                    ('GUEST', 'GUEST')
                ],
                default='BUYER'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(
                max_length=100,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.CharField(
                max_length=100,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(
                max_length=100,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(
                max_digits=9,
                decimal_places=6,
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(
                max_digits=9,
                decimal_places=6,
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(
                max_length=10,
                default='hi'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='guest_token',
            field=models.CharField(
                max_length=64,
                blank=True,
                null=True,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='udhaar_limit',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                default=20000.00
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='current_udhaar',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                default=0.00
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_enabled',
            field=models.BooleanField(
                default=False
            ),
        ),
    ]
